# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "D:\\proga\\ShopMicroservices\\src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/Basket.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basketapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\pin11\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\proga\\ShopMicroservices\\src\\Services\\Basket\\Basket.API:/app:rw"
    - "D:\\proga\\ShopMicroservices\\src:/src:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "D:\\proga\\ShopMicroservices\\src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\pin11\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\proga\\ShopMicroservices\\src\\Services\\Catalog\\Catalog.API:/app:rw"
    - "D:\\proga\\ShopMicroservices\\src:/src:rw"
    working_dir: "/app"
